name: continous delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: simulando Continous delivery
        run: echo "Simulando Continous delivery"

      - name: Upload projeto
        uses: actions/upload-artifact@v7
        with:
          name: projetozipado
          path: |
            **/*.py
            README.md


  docker:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Download projeto
        uses: actions/download-artifact@v8
        with:
          name: projetozipado

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: user/app:latest