name: continous delivery

on:
  push:
    branches:
      - main #ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: simulando Continous elivery

      - uses: actions/upload-artifact@v7
        with:
          name: projetozipado.zip
          path: |
            '**.py'
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/upload-artifact@v7
        with:
          name: projetozipado.zip
          path: |
      - name: Display structure of download files
        run : ls -R